import type { VideoModel } from "./types";
import { FEATURED_MODEL_IDS } from "./model-catalog";

const seconds = (from: number, to: number) => Array.from({ length: to - from + 1 }, (_, i) => i + from);
const seedanceRatios = ["21:9", "16:9", "4:3", "1:1", "3:4", "9:16"];
const klingRatios = ["16:9", "9:16", "1:1"];
const veoRatios = ["16:9", "9:16"];

export const MODEL_ORDER = FEATURED_MODEL_IDS;

export const MODEL_FALLBACKS: Record<string, VideoModel> = {
  "google/veo-3.1": {
    id: "google/veo-3.1",
    name: "Google: Veo 3.1",
    description: "Google's highest-fidelity Veo tier for final production, synchronized audio and frame-guided video.",
    supported_durations: [4, 6, 8],
    supported_resolutions: ["1080p", "4K"],
    supported_aspect_ratios: veoRatios,
    supported_frame_images: ["first_frame", "last_frame"],
    generate_audio: true,
    pricing_skus: { "fallback-1080p-no-audio-second": 0.20, "fallback-1080p-audio-second": 0.40, "fallback-4K-no-audio-second": 0.40, "fallback-4K-audio-second": 0.60 },
    fallback: true,
  },
  "google/veo-3.1-lite": {
    id: "google/veo-3.1-lite",
    name: "Google: Veo 3.1 Lite",
    description: "Cost-efficient Veo 3.1 tier for high-volume iteration with synchronized audio.",
    supported_durations: [4, 6, 8],
    supported_resolutions: ["720p", "1080p"],
    supported_aspect_ratios: veoRatios,
    supported_frame_images: ["first_frame", "last_frame"],
    generate_audio: true,
    pricing_skus: { "fallback-720p-no-audio-second": 0.03, "fallback-720p-audio-second": 0.05, "fallback-1080p-no-audio-second": 0.05, "fallback-1080p-audio-second": 0.08 },
    fallback: true,
  },
  "google/veo-3.1-fast": {
    id: "google/veo-3.1-fast",
    name: "Google: Veo 3.1 Fast",
    description: "Mid-tier Veo 3.1 balancing turnaround, quality and native synchronized audio.",
    supported_durations: [4, 6, 8],
    supported_resolutions: ["720p", "1080p"],
    supported_aspect_ratios: veoRatios,
    supported_frame_images: ["first_frame", "last_frame"],
    generate_audio: true,
    pricing_skus: { "fallback-no-audio-second": 0.08, "fallback-audio-second": 0.10 },
    fallback: true,
  },
  "openai/sora-2-pro": {
    id: "openai/sora-2-pro",
    name: "OpenAI: Sora 2 Pro",
    description: "Production-quality Sora video with synchronized audio, persistent world state and image guidance.",
    supported_durations: [4, 8, 12, 16, 20],
    supported_resolutions: ["720p", "1080p"],
    supported_aspect_ratios: ["16:9", "9:16"],
    supported_frame_images: ["first_frame"],
    generate_audio: true,
    pricing_skus: { "fallback-720p-second": 0.30, "fallback-1080p-second": 0.50 },
    fallback: true,
  },
  "bytedance/seedance-1-5-pro": {
    id: "bytedance/seedance-1-5-pro",
    name: "ByteDance: Seedance 1.5 Pro",
    description: "Audio-visual Seedance generation with multilingual lip-sync and first/last-frame control.",
    supported_durations: seconds(4, 12),
    supported_resolutions: ["480p", "720p", "1080p"],
    supported_aspect_ratios: seedanceRatios,
    supported_frame_images: ["first_frame", "last_frame"],
    generate_audio: true,
    pricing_skus: { "fallback-480p-audio-second": 0.02306, "fallback-480p-no-audio-second": 0.01153 },
    fallback: true,
  },
  "bytedance/seedance-2.0-fast": {
    id: "bytedance/seedance-2.0-fast",
    name: "ByteDance: Seedance 2.0 Fast",
    description: "Fast Seedance 2.0 variant for lower-cost multimodal iteration and reference-driven video.",
    supported_durations: seconds(4, 15),
    supported_resolutions: ["480p", "720p"],
    supported_aspect_ratios: seedanceRatios,
    supported_frame_images: ["first_frame", "last_frame"],
    generate_audio: true,
    pricing_skus: { "fallback-480p-second": 0.04035, "fallback-720p-second": 0.121 },
    fallback: true,
  },
  "bytedance/seedance-2.0-mini": {
    id: "bytedance/seedance-2.0-mini",
    name: "ByteDance: Seedance 2.0 Mini",
    description: "Fast, cost-efficient iteration with multimodal references and first/last-frame control.",
    supported_durations: seconds(4, 15),
    supported_resolutions: ["480p", "720p"],
    supported_aspect_ratios: seedanceRatios,
    supported_frame_images: ["first_frame", "last_frame"],
    generate_audio: true,
    pricing_skus: { "fallback-480p-second": 0.01345, "fallback-720p-second": 0.03024 },
    fallback: true,
  },
  "bytedance/seedance-2.5": {
    id: "bytedance/seedance-2.5",
    name: "ByteDance: Seedance 2.5",
    description: "Reference-heavy, multilingual audiovisual generation for complex product and UGC workflows.",
    supported_durations: seconds(4, 30),
    supported_resolutions: ["480p", "720p"],
    supported_aspect_ratios: [...seedanceRatios, "9:21"],
    supported_frame_images: ["first_frame", "last_frame"],
    generate_audio: true,
    pricing_skus: { "fallback-480p-second": 0.1028, "fallback-720p-second": 0.2311 },
    fallback: true,
  },
  "bytedance/seedance-2.0": {
    id: "bytedance/seedance-2.0",
    name: "ByteDance: Seedance 2.0",
    description: "Strong reference consistency, visual style preservation and camera movement control.",
    supported_durations: seconds(4, 15),
    supported_resolutions: ["480p", "720p"],
    supported_aspect_ratios: seedanceRatios,
    supported_frame_images: ["first_frame", "last_frame"],
    generate_audio: true,
    pricing_skus: { "fallback-480p-second": 0.06726, "fallback-720p-second": 0.1512 },
    fallback: true,
  },
  "kwaivgi/kling-v3.0-pro": {
    id: "kwaivgi/kling-v3.0-pro",
    name: "Kling: Video v3.0 Pro",
    description: "Premium Kling tier for higher visual quality, image guidance and native audio.",
    supported_durations: seconds(3, 15),
    supported_resolutions: ["720p"],
    supported_aspect_ratios: klingRatios,
    supported_frame_images: ["first_frame", "last_frame"],
    generate_audio: true,
    pricing_skus: { "fallback-no-audio-second": 0.112, "fallback-audio-second": 0.168 },
    fallback: true,
  },
  "kwaivgi/kling-v3.0-std": {
    id: "kwaivgi/kling-v3.0-std",
    name: "Kling: Video v3.0 Standard",
    description: "Lower-cost Kling 3.0 tier for production iteration with first/last frames and native audio.",
    supported_durations: seconds(3, 15),
    supported_resolutions: ["720p"],
    supported_aspect_ratios: klingRatios,
    supported_frame_images: ["first_frame", "last_frame"],
    generate_audio: true,
    pricing_skus: { "fallback-no-audio-second": 0.084, "fallback-audio-second": 0.126 },
    fallback: true,
  },
  "kwaivgi/kling-video-o1": {
    id: "kwaivgi/kling-video-o1",
    name: "Kling: Video O1",
    description: "Cinematic short-form Kling model with 5/10 second clips and guided frame composition.",
    supported_durations: [5, 10],
    supported_resolutions: ["720p"],
    supported_aspect_ratios: klingRatios,
    supported_frame_images: ["first_frame", "last_frame"],
    generate_audio: false,
    pricing_skus: { "fallback-second": 0.112 },
    fallback: true,
  },
  "runway/gen-4.5": {
    id: "runway/gen-4.5",
    name: "Runway: Gen-4.5",
    description: "Cinematic text/image-to-video model with strong motion, prompt adherence and controlled product reveals.",
    supported_durations: seconds(2, 10),
    supported_resolutions: ["720p"],
    supported_aspect_ratios: ["16:9", "9:16", "4:3", "1:1", "3:4"],
    supported_frame_images: ["first_frame"],
    generate_audio: false,
    pricing_skus: { "fallback-second": 0.12 },
    fallback: true,
  },
  "runway/aleph-2": {
    id: "runway/aleph-2",
    name: "Runway: Aleph 2.0",
    description: "Video-to-video editing model for controlled transformations of existing footage with keyframe guidance.",
    supported_durations: seconds(2, 30),
    supported_resolutions: ["1080p"],
    supported_aspect_ratios: ["16:9", "9:16", "4:3", "3:4", "3:2", "2:3", "1:1", "21:9"],
    supported_frame_images: [],
    generate_audio: false,
    workflow: "video_edit",
    pricing_skus: { "fallback-second": 0.28 },
    fallback: true,
  },
};
